service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    GIT_API_TOKEN: ${ssm:gitToken}

functions:
  moveCard:
    handler: handler.moveCard
    events:
      - http:
          method: post
          path: movecard
          cors: true
